name: PhoneLM-1.5B-DroidCall
wandb: False
resume: False
profile: False
training:
    base_dir: "../data/xllm-best_ckpt/xllm_sft"
    use_bf16: True
    context_size: 2048
    num_train_epochs: 24
    learning_rate: 1.41e-5
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_epsilon: 1e-8
    weight_decay: 0.1
    deepspeed_config: "./ds_config_decaylr.json"
    per_device_train_batch_size: 2
    per_device_eval_batch_size: 2
    gradient_accumulation_steps: 16
    set_logging_steps: 1
    set_compute_metrics: False
    bad_epochs_limit: 5
    warmup_ratio: 0.1
    set_eval_steps: 2
    set_save_steps: 2

    use_lora: True
lora:
    lora_alpha: 16
    r: 8
    dropout: 0.0
model:
    tokenizer_path: "./tokenizer"  
datasets:
    path: "./train_datasets_instruct"
    val_rate: 0.005
    packing: False
    data_type: "json"
